### ISSUE TITLE
Blog redesign

### ISSUE THREAD

**Issue by akshayrawat** [soumyaveer/soumyaveer.github.io#23] opened 2018-03-11 03:54 UTC
Examples: 

* https://drivy.engineering/

Top level sections:

* Home - default
* Technical
* Book Worm
* Sketches
* About / Resume

**Comment by soumyaveer** [comment] 2018-04-07 19:59
Duplicate of https://github.com/soumyaveer/course-work/issues/37

**Closed as completed by soumyaveer** 2018-04-07 19:59 UTC
